apiVersion: v1
kind: Service
metadata:

  name: nodeport
  namespace: default

spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  {{- with .Values.service}}
  ports:
  {{- with .front}}
  - name: {{ .name}}
    nodePort: {{ .nodePort}}
    port: {{ .port}}
    protocol: TCP
    targetPort: {{ .targetPort}}
  {{- end}}
  {{- with .back}}
  - name: {{.name}}
    port: {{.port}}
    nodePort: {{.nodePort}}
    protocol: TCP
    targetPort: {{.targetPort}}
  selector:
    app : server
  {{- end}}
  sessionAffinity: None
  type: {{ .type }}
  {{- end}}
