apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: back 
spec:
  containers:
  - name: backend
    image: 0om4r/todo_1:ubu.nginx.1
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
