apiVersion: v1
kind: Service
metadata:
  name: be
  namespace: default


spec:

  selector:
    app: back
  ports:
  - name: back
    port: 5000
    nodePort: 30008
    protocol: TCP
    targetPort: 5000
  type: NodePort
