version: '3'
services:  
  db: 
    image: mysql
    
    volumes:
      - mysql_volume:/var/lib/mysql/
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PORT: "${MYSQL_PORT}"
    container_name: db_mysql
    healthcheck:
      test: mysqladmin ping -h ${MYSQL_HOST} -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  go-test1: 
    image: go-test
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_HOST: "${MYSQL_HOST}"
    ports:
    - 8080:8081
    depends_on:
      db:
        condition: service_healthy

   
    container_name: goApp 
    
volumes:
  mysql_volume:
    driver: local