version: '3'
services:  
  
  todo_backend: 
    build: ./backend
    environment: 
      - DB_FILE="./todo.db"
      - Port=":5000"
    ports:
      - 5000:5000
    container_name: goApp
    volumes:
      - go-todo:/home/tmp
    restart: always


    ## 
  todo_frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - todo_backend
volumes: 
    go-todo: 
    