apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: front 
spec:
  containers:
  - name: frontend
    image: 0om4r/todo_1:end
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: BACKEND_URL
      value: "http://192.168.59.100:30008/"