apiVersion: v1
kind: Service
metadata:

  name: nodeport
  namespace: default

spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: frontend
    nodePort: 30007
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}