name: Go

on:
  push:
    branches: 
      - main
      - omarTest
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - 
      name: Build
      run: go build -v ./...
      
    - 
      name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo_1:sqlite
